"""empty message

Revision ID: 3e90eebb6663
Revises: 2f6f1f25569f
Create Date: 2026-04-06 23:05:41.364657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e90eebb6663'
down_revision: Union[str, Sequence[str], None] = '2f6f1f25569f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_projects_owner_id_users', 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_owner_id_users', 'projects', type_='foreignkey')
    # ### end Alembic commands ###
