services:

  postgres:
    image: postgres:16
    container_name: fast_architectury_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - fast-architectury-net

  redis:
    image: redis:7-alpine
    container_name: fast_architectury_redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - fast-architectury-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fast_architectury_rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - fast-architectury-net

  minio:
    image: minio/minio
    container_name: fast_architectury_minio
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - fast-architectury-net

  fastapi:
    build: ./app
    image: fastapi-architectury-fastapi
    container_name: fast_architectury_fastapi
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: >
      bash -c "alembic upgrade head &&
      gunicorn -b 0.0.0.0:8000
      -w 2
      -t 120
      -k uvicorn.workers.UvicornWorker
      main:app
      --max-requests 1000
      --max-requests-jitter 100
      --access-logfile -"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - fast-architectury-net

  worker:
    build: ./app
    image: fastapi-architectury-worker
    container_name: fast_architectury_worker
    env_file:
      - .env
    command: celery -A worker.celery_app:celery_app worker -l info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - fast-architectury-net

#  watchtower:
#    image: containrrr/watchtower
#    container_name: watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: --interval 60
#    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
  redis_data:
  minio_data:

networks:
  fast-architectury-net:
    external: true