name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract metadata
        id: meta
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          echo "image=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.meta.outputs.image }}:latest ./app

      - name: Push Docker image
        run: |
          docker push ${{ steps.meta.outputs.image }}:latestd